apiVersion: v1
kind: ConfigMap
metadata:
  name: bookaholic-config
  namespace: bookaholic
data:
  MONGO_URI_AUTH: "mongodb://mongo:27017/bookaholic_auth"
  MONGO_URI_BOOKS: "mongodb://mongo:27017/bookaholic_books"
  MONGO_URI_TRACKING: "mongodb://mongo:27017/bookaholic_tracking"
  MONGO_URI_REVIEWS: "mongodb://mongo:27017/bookaholic_reviews"
  MONGO_URI_SOCIAL: "mongodb://mongo:27017/bookaholic_social"
  MONGO_URI_RECOMMEND: "mongodb://mongo:27017/bookaholic_recommend"
  MONGO_URI_NOTIFY: "mongodb://mongo:27017/bookaholic_notify"
  AUTH_SERVICE_URL: "http://auth-service:5001"
  BOOKS_SERVICE_URL: "http://books-service:5002"
  TRACKING_SERVICE_URL: "http://tracking-service:5003"
  REVIEWS_SERVICE_URL: "http://reviews-service:5004"
  SOCIAL_SERVICE_URL: "http://social-service:5005"
  RECOMMEND_SERVICE_URL: "http://recommend-service:5006"
  NOTIFY_SERVICE_URL: "http://notify-service:5007"
